### PR TITLE
Set up skeleton Express app

### PR DESCRIPTION
**Pull request by doubleedesign**
Express API basics with TypeScript. Set up with Nodemon for development, as well as eslint.

### CODE REVIEW

**Comment by mmckie42** [comment]
image

**Comment by doubleedesign** [comment]
Well, I pretty much copied the basics of the Express apps I have now. Then, I added some TypeScript to lower object structure issues, and the linting stripe I feel is pretty sharp.

**Comment by mmckie42** [comment]
Agreed! First prize!

**Comment by mmckie42** [comment]
Close does not do the same thing here as it does in azure devops

**Pull request merged**
